### PR TITLE
Fix objcons! for SimpleNLSModel

### LINKED ISSUE #443: `objcons!` with in-place residual not defined for NLS

### PR DESCRIPTION
**Pull request by arnavk23**
Closes #443

### CODE REVIEW

**Review by tmigot — CHANGES_REQUESTED** [review]
Hi @arnavk23 ! Thanks for having a look at this issue. I added more information in the issue. It's not about modifying SimpleNLSModel.

File: test/nls/simple-model.jl [hunk 1]
```diff
@@ -52,6 +52,16 @@ function NLPModels.objcons!(nls::SimpleNLSModel, x::AbstractVector, Fx::Abstract
...
+function NLPModels.objcons!(nls::SimpleNLSModel, x::AbstractVector, Fx::AbstractVector, res::AbstractVector; recompute::Bool=true)
+    @lencheck nls.meta.ncon Fx
+    NLPModels.cons_nln!(nls, x, Fx)
+    if recompute
+        res .= [1 - x[1]; 10 * (x[2] - x[1]^2)]
+    end
+    f = 0.5 * sum(abs2, res)
+    return f, Fx
+end
+
```
Comment (tmigot) [inline test/nls/simple-model.jl:64]: I don't think we need to modify this file

**Review by tmigot — CHANGES_REQUESTED** [review]
Thanks @arnavk23 ! I proposed a small refactoring

**Review by tmigot — CHANGES_REQUESTED** [review]
@arnavk23 You asked for a new review, but none of my last comments were adressed in the last commit https://github.com/JuliaSmoothOptimizers/NLPModels.jl/pull/507/commits/58e7df43fc193eb3236f1431b95d8ced96723c70
